FROM ubuntu:18.04
RUN apt-get update && apt-get install -y git curl ca-certificates unzip xz-utils && \
    useradd rancher && \
    mkdir -p /var/lib/rancher/etcd /var/lib/cattle && \
    chown -R rancher /var/lib/rancher /var/lib/cattle /usr/local/bin
RUN mkdir /root/.kube && \
    ln -s /usr/bin/rancher /usr/bin/kubectl && \
    ln -s /var/lib/rancher/management-state/cred/kubeconfig.yaml /root/.kube/config && \
    ln -s /usr/bin/rancher /usr/bin/reset-password && \
    ln -s /usr/bin/rancher /usr/bin/ensure-default-admin && \
    rm -f /bin/sh && ln -s /bin/bash /bin/sh
WORKDIR /var/lib/rancher

ARG ARCH=amd64
ENV CATTLE_HELM_VERSION v2.10.0-rancher10
ENV CATTLE_MACHINE_VERSION v0.15.0-rancher6-1
ENV LOGLEVEL_VERSION v0.1.2
ENV TINI_VERSION v0.18.0
ENV TELEMETRY_VERSION v0.5.3
ENV CACHEDIR ftp://39.106.101.34/rancherserver_build_cache


RUN curl -sLf ${CACHEDIR}/rancher/machine-package/releases/download/${CATTLE_MACHINE_VERSION}/docker-machine-${ARCH}.tar.gz | tar xvzf - -C /usr/bin && \
    curl -sLf ${CACHEDIR}/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz | tar xvzf - -C /usr/bin

ENV TINI_URL_amd64=${CACHEDIR}/krallin/tini/releases/download/${TINI_VERSION}/tini \
    TINI_URL_arm64=${CACHEDIR}/krallin/tini/releases/download/${TINI_VERSION}/tini-arm64 \
    TINI_URL=TINI_URL_${ARCH}

ENV HELM_URL_amd64=${CACHEDIR}/rancher/helm/releases/download/${CATTLE_HELM_VERSION}/helm \
    HELM_URL_arm64=${CACHEDIR}/rancher/helm/releases/download/${CATTLE_HELM_VERSION}/helm-arm64 \
    HELM_URL=HELM_URL_${ARCH} \
    TILLER_URL_amd64=${CACHEDIR}/rancher/helm/releases/download/${CATTLE_HELM_VERSION}/tiller \
    TILLER_URL_arm64=${CACHEDIR}/rancher/helm/releases/download/${CATTLE_HELM_VERSION}/tiller-arm64 \
    TILLER_URL=TILLER_URL_${ARCH}

RUN curl -sLf ${!TINI_URL} > /usr/bin/tini && \
    curl -sLf ${!HELM_URL} > /usr/bin/helm && \
    curl -sLf ${!TILLER_URL} > /usr/bin/tiller && \
    curl -sLf ${CACHEDIR}/rancher/telemetry/releases/download/${TELEMETRY_VERSION}/telemetry-${ARCH} > /usr/bin/telemetry && \
    chmod +x /usr/bin/helm /usr/bin/tini /usr/bin/telemetry /usr/bin/tiller

ENV CATTLE_UI_PATH /usr/share/rancher/ui
ENV CATTLE_UI_VERSION 2.2.4
ENV CATTLE_CLI_VERSION v2.2.0-rc13

# Please update the api-ui-version in pkg/settings/settings.go when updating the version here.
ENV CATTLE_API_UI_VERSION 1.1.6

RUN mkdir -p /var/log/auditlog
ENV AUDIT_LOG_PATH /var/log/auditlog/rancher-api-audit.log
ENV AUDIT_LOG_MAXAGE 10
ENV AUDIT_LOG_MAXBACKUP 10
ENV AUDIT_LOG_MAXSIZE 100
ENV AUDIT_LEVEL 1
VOLUME /var/log/auditlog

RUN mkdir -p /usr/share/rancher/ui
COPY 2.1.4.tar.gz /usr/share/rancher/ui
RUN cd /usr/share/rancher/ui && \
    tar xvzf 2.1.4.tar.gz --strip-components=1 && \
    cd /var/lib/rancher
#    mkdir -p /usr/share/rancher/ui/api-ui && \
#    cd /usr/share/rancher/ui/api-ui && \
#    curl -sL https://releases.rancher.com/api-ui/${CATTLE_API_UI_VERSION}.tar.gz | tar xvzf - --strip-components=1 && \


ENV CATTLE_CLI_URL_DARWIN  https://releases.rancher.com/cli2/${CATTLE_CLI_VERSION}/rancher-darwin-amd64-${CATTLE_CLI_VERSION}.tar.gz
ENV CATTLE_CLI_URL_LINUX   https://releases.rancher.com/cli2/${CATTLE_CLI_VERSION}/rancher-linux-amd64-${CATTLE_CLI_VERSION}.tar.gz
ENV CATTLE_CLI_URL_WINDOWS https://releases.rancher.com/cli2/${CATTLE_CLI_VERSION}/rancher-windows-386-${CATTLE_CLI_VERSION}.zip


### ---- go complie environment ------
COPY apt-src /etc/apt/sources.list
RUN apt-get update && apt-get upgrade -y && apt-get install golang -y 
RUN apt-get install vim -y 

ENV GOROOT /usr/lib/go-1.10/
ENV GOPATH /data/go
ENV PATH $GOROOT/bin:$PATH


ARG VERSION=v1.1
ENV CATTLE_SERVER_VERSION ${VERSION}
COPY entrypoint.sh rancher scripts/start-rancher scripts/compile-rancher scripts/go-rancher /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh && chmod +x /usr/bin/start-rancher && chmod +x /usr/bin/compile-rancher

ENV CATTLE_AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV CATTLE_WINDOWS_AGENT_IMAGE rancher/rancher-agent:${VERSION}-nanoserver-1803
ENV CATTLE_SERVER_IMAGE rancher/rancher
ENV ETCD_UNSUPPORTED_ARCH=${ARCH}

ENV SSL_CERT_DIR /etc/rancher/ssl
VOLUME /var/lib/rancher


### --- prevent Ctrl+C direct exit contaioner ------
# ENTRYPOINT ["entrypoint.sh"]
CMD ["/bin/bash"]



