FROM ubuntu:18.04
ARG ARCH=amd64
ENV CACHEDIR ftp://39.106.101.34/agent_build_cache
ENV DOCKER_URL_amd64=${CACHEDIR}/builds/Linux/x86_64/docker-1.10.3 \
    DOCKER_URL_arm64=${CACHEDIR}/rancher/docker/releases/download/v1.10.3-ros1/docker-1.10.3_arm64 \
    DOCKER_URL=DOCKER_URL_${ARCH}


RUN rm -f /bin/sh && ln -s /bin/bash /bin/sh
RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates jq iproute2 vim-tiny less bash-completion unzip sysstat && \
    curl -sLf ${!DOCKER_URL} > /usr/bin/docker && \
    chmod +x /usr/bin/docker && \
    curl -sLf ${CACHEDIR}/kubernetes-release/release/v1.12.6/bin/linux/${ARCH}/kubectl > /usr/bin/kubectl && \
    chmod +x /usr/bin/kubectl && \
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y && \
    DEBIAN_FRONTEND=noninteractive apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
ENV LOGLEVEL_VERSION v0.1.2

RUN curl -sLf ${CACHEDIR}/rancher/loglevel/releases/download/${LOGLEVEL_VERSION}/loglevel-${ARCH}-${LOGLEVEL_VERSION}.tar.gz | tar xvzf - -C /usr/bin
RUN curl -sL ${CACHEDIR}/rancher/share-mnt/releases/download/v1.0.4/share-mnt-${ARCH}.tar.gz | tar xvzf - -C /usr/bin
ENV KUBEPROMPT_VERSION v1.0.6

RUN curl -sL ${CACHEDIR}/c-bata/kube-prompt/releases/download/${KUBEPROMPT_VERSION}/kube-prompt_${KUBEPROMPT_VERSION}_linux_${ARCH}.zip > /usr/bin/kube-prompt.zip && unzip /usr/bin/kube-prompt.zip -d /usr/bin
ARG VERSION=dev
LABEL io.cattle.agent true
ENV DOCKER_API_VERSION 1.24
ENV AGENT_IMAGE rancher/rancher-agent:${VERSION}
ENV SSL_CERT_DIR /etc/kubernetes/ssl/certs
COPY agent run.sh kubectl-shell.sh shell-setup.sh share-root.sh /usr/bin/
ENTRYPOINT ["run.sh"]
